# print("hey isha please give me your number : ")
# number=input("hey isha please give me your number : ")
# print(type(number))
num1=float(input("Enter first number :"))
num2=float(input("Enter 2nd number  :"))
print(num1+num2)